# Generated by Django 5.2.8 on 2025-12-02 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationtoken_loginhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'verbose_name': 'Email Verification Token', 'verbose_name_plural': 'Email Verification Tokens'},
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='emailverificationtoken',
            table='email_verifications_tokens',
        ),
    ]
